### PR TITLE
Add `NodeStatus` `Debug` impl

### PR DESCRIPTION
**Pull request by jgrund**
Signed-off-by: Joe Grund <jgrund@whamcloud.io>

### CODE REVIEW

**Comment by chrissie-c** [comment]
It looks like this one still needs a rebase too (sorry, after seeing your last commit I decided to do some work on the project!)

**Comment by jgrund** [comment]
> It looks like this one still needs a rebase too (sorry, after seeing your last commit I decided to do some work on the project!)

I might be missing it, but it looks like b512e796f956133c06bf7f2171e9ac575e2b4124 is latest?

**Comment by jgrund** [comment]
> > It looks like this one still needs a rebase too (sorry, after seeing your last commit I decided to do some work on the project!)
> 
> I might be missing it, but it looks like [b512e79](https://github.com/chrissie-c/rust-corosync/commit/b512e796f956133c06bf7f2171e9ac575e2b4124) is latest?

Hrrm, this is currently based on b512e796f956133c06bf7f2171e9ac575e2b4124. Do you want me to move the rustfmt changes to a separate patch?

**Comment by chrissie-c** [comment]
Oh. that's very strange. github is showing your patch as adding my existing changes to quorum-test.rs (but only that test!).

**Comment by jgrund** [comment]
> Oh. that's very strange. github is showing your patch as adding my existing changes to quorum-test.rs (but only that test!).

I think that might be due to the rustfmt changes on that file. I'll split it out to a separate PR.

**Comment by chrissie-c** [comment]
OK, I see what happened. yes it is just rustfmt changes (I hadn't refreshed the patch). yes. please add that as a separate patch (it can go in this PR if you like, so long as it's a new commit

Thanks

**Comment by jgrund** [comment]
Ok, formatting removed from this patch and pushed under #4

**Comment by chrissie-c** [comment]
Great, thank you!

**Pull request merged**
